package org.openqa.core.enums;

public class PropertiesTitles {
	
	
	public static final String[] PERSON_PROPERTIES = {
		"AGE", 
		"ANCESTOR", 
		"CAUSEOFDEATH", 
		PropertyEnum.DATEOFBIRTH.name(), 
		"DATEOFDEATH", 
		"DATEOFLIVING", 
		"DATEOFMARRIAGE", 
		"FOOD", 
		"HABITAT", 
		"HEIGHT", 
		"IDENTITY", 
		"INCOME", 
		"KILLER", 
		"LANGUAGE", 
		"LIFESPAN", 
		"NAME", 
		"NATIONALITY", 
		"PLACEOFBIRTH", 
		"PLACEOFDEATH", 
		"PLACEOFLIVING", 
		"PROFESSION", 
		"SIZE", 
		"SPECIALTY"
		};
	public static final String[] ORGANIZATION_PROPERTIES = {
		"ABBREVIATION", 
//		"ACTOR", 
		"AGE", 
		"DATEOFFOUNDATION", 
		"DATEOFSTARTOFOPERATION", 
		"FOUNDER", 
		"FUNCTION", 
		"HABITAT", 
		"INCOME", 
		"LANGUAGE", 
		"LEADER", 
		"LONGFORM", 
		"NAME", 
		"NATIONALITY", 
		"OWNER", 
		"PLACEOFORIGIN", 
		"SPECIALTY", 
		"SYNONYM", 
		"VALUE"
		};
	public static final String[] EVENT_PROPERTIES = {
//		"ABBREVIATION", 
		"ACTOR", 
//		"AGE", 
		"CAUSE", 
		"CONSEQUENCE", 
		"DATE", 
//		"DATEOFCREATION", 
//		"DATEOFEND", 
//		"DATEOFSTART", 
//		"DURATION", 
//		"HABITAT", 
//		"LANGUAGE", 
//		"NAME", 
		"PLACE", 
//		"SYNONYM", 
//		"VALUE", 
//		"WINNER"
		};
	public static final String[] THING_PROPERTIES = {
		"ABBREVIATION", 
		"AGE", 
		"AUTHOR", 
		"BUILDER", 
		"CAPITAL", 
		"DATEOFCREATION", 
		"DATEOFINVENTION",
		"DATEOFSTARTOFOPERATION", 
		"DEFINITION", 
		"DISCOVERER", 
		"DISCOVERY", 
		"DISTANCE", 
		"EXAMPLE", 
		"FOOD", 
		"FUNCTION", 
		"HEIGHT", 
		"INSTRUMENT", 
		"INVENTOR", 
		"MEDICINE", 
		"NAME", 
		"OWNER", 
		"PLACEOFOCCURRENCE", 
		"PLACEOFORIGIN", 
		"POPULATION", 
		"PROVIDER", 
		"RESOURCE", 
		"SIZE", 
		"SPECIES", 
		"SPEED", 
		"SYMPTOM", 
		"SYNONYM", 
		"TEMPERATURE", 
		"VALUE", 
		"WIDTH"
		};
	public static final String[] ENTERTAINMENT_PROPERTIES = {
		"ACTOR", 
		"AGE", 
		"AUTHOR", 
		"DATEOFCREATION", 
		"DATEOFEND", 
		"DATEOFSTART", 
		"DURATION", 
		"EXAMPLE", 
		"INSTRUMENT", 
		"LANGUAGE", 
		"MOVIE", 
		"NAME", 
		"OWNER", 
		"PLACE", 
		"PLACEOFORIGIN", 
		"SYNONYM", 
		"VALUE"
		};

}
